steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=eu.gcr.io/$PROJECT_ID/isaacranks:$TAG_NAME
  - --cache=true
  - --cache-ttl=336h
timeout: 1h
options:
 machineType: 'N1_HIGHCPU_8'
