name: isaacranks
version: '1.0.7'
license: MIT
dependencies:
- resourcet
- transformers
default-extensions:
  - CPP
  - DeriveDataTypeable
  - DerivingStrategies
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - UndecidableInstances
  - ViewPatterns
library:
  exposed-modules:
  - Application
  - Foundation
  - Import
  - Import.NoFoundation
  - Instrument
  - Items
  - Model
  - Model.IsaacVersion
  - Model.IsaacPool
  - Ranks
  - Settings
  - Settings.StaticFiles
  - Settings.Development
  - Handler.Home
  - Handler.Vote
  - Handler.Ranks
  - Handler.Donate
  - Handler.Changes
  - Handler.Common
  - Vote
  dependencies:
  - base >=4 && <5
  - aeson >=1.4
  - base64-bytestring
  - binary
  - bytestring >=0.9
  - classy-prelude-yesod
  - clientsession
  - clock
  - conduit >=1.0
  - conduit-combinators
  - containers
  - data-default
  - directory >=1.1
  - esqueleto >=3.3
  - extra >=1.4
  - fast-logger >=3.0
  - file-embed
  - hjsmin >=0.1
  - hmatrix
  - http-conduit >=2.1
  - http-types
  - lens
  - lens-aeson >=1.1
  - monad-control >=1.0
  - monad-logger >=0.3.13
  - persistent >=2.0
  - persistent-postgresql >=2.0
  - persistent-template >=2.0
  - prometheus-client >= 0.2.0
  - prometheus-metrics-ghc
  - random
  - random-shuffle
  - shakespeare >=2.0
  - system-filepath
  - template-haskell
  - text >=0.11
  - time
  - uri-bytestring >=0.1
  - vector
  - wai
  - wai-extra >=3.0
  - wai-logger >=2.2
  - wai-middleware-prometheus
  - warp >=3.0
  - wreq >=0.4
  - xml-conduit
  - xml-lens
  - yaml >=0.8
  - yesod >=1.4
  - yesod-auth >=1.4
  - yesod-core >=1.4
  - yesod-form >=1.4
  - yesod-static >=1.5
  - zlib >=0.5
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Werror
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -Wmissing-home-modules
      - -Widentities
      - -Wcpp-undef
      - -Wmissing-export-lists
      - -Wmonomorphism-restriction
      - -fwarn-tabs
      - -O2
executables:
  rebuildranks:
    main: rebuild.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - '"-with-rtsopts=-N -T"'
    dependencies:
    - base
    - isaacranks
    - yesod
    - persistent
    - persistent-postgresql
    - monad-logger
    - time
    when:
    - condition: flag(library-only)
      buildable: false
  isaacranks:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - '"-with-rtsopts=-N -T"'
    dependencies:
    - base
    - isaacranks
    - yesod
    when:
    - condition: flag(library-only)
      buildable: false
  load-data:
    main: load.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - '"-with-rtsopts=-N -T"'
    dependencies:
    - base
    - isaacranks
    - yesod
    - persistent
    - persistent-postgresql
    - monad-logger
    when:
    - condition: flag(library-only)
      buildable: false
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - base
    - isaacranks
    - yesod-test >=1.4
    - yesod-core
    - yesod
    - persistent
    - persistent-postgresql
    - monad-logger
    - hspec
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
