name: isaacranks
version: '1.0.0'
license: MIT
dependencies:
- resourcet
- transformers
default-extensions:
  - CPP
  - DeriveDataTypeable
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - ViewPatterns
library:
  exposed-modules:
  - Application
  - Foundation
  - Import
  - Import.NoFoundation
  - Instrument
  - Items
  - Model
  - Model.IsaacVersion
  - Model.IsaacPool
  - Settings
  - Settings.StaticFiles
  - Settings.Development
  - Handler.Home
  - Handler.Vote
  - Handler.Ranks
  - Handler.Donate
  - Handler.Changes
  - Handler.Common
  - Vote
  dependencies:
  - base >=4 && <5
  - aeson >=1.0 && <1.1
  - amazonka >=1.3 && <1.5
  - amazonka-s3 >=1.3 && <1.5
  - base64-bytestring
  - binary
  - bytestring >=0.9 && <0.11
  - classy-prelude-yesod
  - clientsession
  - clock
  - conduit >=1.0 && <2.0
  - conduit-combinators
  - containers
  - data-default
  - directory >=1.1 && <1.4
  - esqueleto >=2.4 && <2.6
  - extra >=1.4 && <1.6
  - fast-logger >=2.3 && <2.5
  - file-embed
  - hjsmin >=0.1 && <0.3
  - http-conduit >=2.1 && <2.3
  - http-types
  - lens
  - lens-aeson >=1.0 && <1.1
  - monad-control >=1.0 && <1.1
  - monad-logger >=0.3.13 && <0.4
  - persistent >=2.0 && <2.7
  - persistent-postgresql >=2.0 && <2.7
  - persistent-template >=2.0 && <2.7
  - prometheus-client
  - prometheus-metrics-ghc
  - random
  - random-shuffle
  - shakespeare >=2.0 && <2.1
  - system-filepath
  - template-haskell
  - text >=0.11 && <2.0
  - time
  - uri-bytestring >=0.1 && <0.3
  - wai
  - wai-extra >=3.0 && <3.1
  - wai-logger >=2.2 && <2.4
  - wai-middleware-prometheus
  - warp >=3.0 && <3.3
  - wreq >=0.4 && <0.6
  - xml-conduit
  - xml-lens
  - yaml >=0.8 && <0.9
  - yesod >=1.4 && <1.5
  - yesod-auth >=1.4 && <1.5
  - yesod-core >=1.4 && <1.5
  - yesod-form >=1.4 && <1.5
  - yesod-static >=1.5 && <1.6
  - zlib >=0.5 && <0.7
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
executables:
  rebuildranks:
    main: rebuild.hs
    source-dirs: app
    ghc-options:
    - -O2
    - -rtsopts
    dependencies:
    - base
    - isaacranks
    - yesod
    - persistent
    - persistent-postgresql
    - monad-logger
    - time
    when:
    - condition: flag(library-only)
      buildable: false
  isaacranks:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - isaacranks
    - yesod
    when:
    - condition: flag(library-only)
      buildable: false
  load-data:
    main: load.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -O2
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - isaacranks
    - yesod
    - persistent
    - persistent-postgresql
    - monad-logger
    when:
    - condition: flag(library-only)
      buildable: false
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - base
    - isaacranks
    - yesod-test >=1.4 && <1.6
    - yesod-core
    - yesod
    - persistent
    - persistent-postgresql
    - monad-logger
    - hspec
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
