# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: isaacranks
  password: isaacranks
  host: localhost
  port: 5432
  database: isaacranks
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: isaacranks_test
  <<: *defaults

Staging:
  database: isaacranks_staging
  poolsize: 100
  <<: *defaults

Production:
  database: isaacranks_production
  poolsize: 100
  <<: *defaults
